services:
  wishlist-api:
    build:
      context: ./wishlist-api
      target: development
    container_name: wishlist-api
    restart: on-failure
    ports:
      - "5050:5050"
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://admin:password@mongodb:27017/wishlist?authSource=admin
      MONGO_TEST_URL: mongodb://admin:password@mongodb:27017/wishlist-test?authSource=admin
      PORT: 5050
    volumes:
      - ./wishlist-api:/app
      - /app/node_modules    
    depends_on:
      - mongodb

  wishlist-bff:
    build:
      context: ./wishlist-bff
      target: development
    container_name: wishlist-bff
    restart: on-failure
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
      WISHLIST_API_URL: http://wishlist-api:5050
      JWT_SECRET: secret-jwt-key
    volumes:
      - ./wishlist-bff:/app
      - /app/node_modules    


  mongodb:
    image: mongo:7.0
    container_name: wishlist-mongodb
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: wishlist
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local